sudo: false

language: node_js

node_js:
  - "node"

install:
  - npm install
  - npm install codecov -g

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - NODE_ENV=CI
    - CXX=g++-4.8

jobs:
  include:
    - stage: test
      services:
        - postgresql
        - docker
      addons:
        postgresql: "9.6"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - bc
      before_script:
        - psql -c 'create database agado_test;' -U postgres
      env:
        - DB_HOST=localhost
        - DB_DATABASE=agado_test
        - DB_USER=postgres
        - DB_PASSWORD=
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
      script: 
        # - npm run lint
        - npm run migrate
        - npm run test-coverage-ci
        - docker build .
        - docker build frontend
      after_success:
        - codecov
    - stage: deploy
      if: branch = master
      services:
        - docker
      script:
        - chmod +x ./deploy-ci.sh
        - ./deploy-ci.sh
      skip_cleanup: true

before_install:
  - eval "${MATRIX_EVAL}"
