#######################################################
# THIS DOCKER COMPOSE IS INTENDED FOR LOCAL TEST ONLY.#
# DO NOT USE IN PRODUCTION ENVIRONMENT.               #
#######################################################
version: '3'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./database/db_storage:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agado
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      TZ: 'UTC'
      PGTZ: 'UTC'

  agado-api-svc:
    depends_on:
      - db
    build:
      context: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_TTL: "99999m"
      JWT_SECRET: "test_secret"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_DATABASE: agado
      DB_USER: root
      DB_PASSWORD: test

  agado-web-svc:
    depends_on:
      - agado-api-svc
    build:
      context: frontend
    expose:
      - "80"
    ports:
      - "8080:80"

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - "8080"
    ports:
      - "9999:8080"
    environment:
      URL: http://localhost:9999/agado/swagger.yaml
    volumes:
      - "./swagger.yaml:/usr/share/nginx/html/agado/swagger.yaml:ro"
