#######################################################
# THIS DOCKER COMPOSE IS INTENDED FOR LOCAL TEST ONLY.#
# DO NOT USE IN PRODUCTION ENVIRONMENT.               #
#######################################################
version: '3'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./database/db_storage:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agado
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      TZ: 'UTC'
      PGTZ: 'UTC'

  app:
    depends_on:
      - db
    build:
      context: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_TTL: "15m"
      JWT_SECRET: "test_secret"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_DATABASE: agado
      DB_USER: root
      DB_PASSWORD: test
